import { Router } from "express";
import { createPlaceholderRoutes } from "./placeholder.routes";
import { createAuthRoutes } from "./auth.routes";
import { createResumeRoutes } from "./resume.routes";
import { createAtsResumeRoutes } from "./ats-resume.routes";
import { createRoadmapRoutes } from "./roadmap.routes";
import { createOnboardingRoutes } from "./onboarding.routes";
import { createJobRoleRoutes, createSkillGapRoutes } from "./skill-gap.routes";
import { createDashboardRoutes } from "./dashboard.routes";
import { createAdminRoutes } from "./admin.routes";
import { createReminderRoutes } from "./reminder.routes";
import { createNotificationRoutes } from "./notification.routes";
import { createBillingRoutes } from "./billing.routes";

export const v1Routes = Router();
v1Routes.use("/auth", createAuthRoutes());
v1Routes.use("/onboarding", createOnboardingRoutes());
v1Routes.use("/job-roles", createJobRoleRoutes());
v1Routes.use("/skill-gap", createSkillGapRoutes());
v1Routes.use("/dashboard", createDashboardRoutes());
v1Routes.use("/users", createPlaceholderRoutes("users"));
v1Routes.use("/profile", createPlaceholderRoutes("profile"));
v1Routes.use("/resumes", createResumeRoutes());
v1Routes.use("/resume-builder", createAtsResumeRoutes());
v1Routes.use("/resume", createPlaceholderRoutes("resume"));
v1Routes.use("/roadmap", createRoadmapRoutes());
v1Routes.use("/reminders", createReminderRoutes());
v1Routes.use("/notifications", createNotificationRoutes());
v1Routes.use("/billing", createBillingRoutes());
v1Routes.use("/ai", createPlaceholderRoutes("ai"));
v1Routes.use("/admin", createAdminRoutes());
