-- Version 1.4: progress tracking and weekly reminder automation.
-- Adds user reminder preferences, activity tracking, durable reminder dedupe keys,
-- and explicit notification/email linkage back to reminder logs.

alter table public.profiles
  add column if not exists last_activity_at timestamptz;

update public.profiles
set last_activity_at = coalesce(updated_at, created_at, now())
where last_activity_at is null;

alter table public.profiles
  alter column last_activity_at set default now();

alter table public.profiles
  alter column last_activity_at set not null;

create index if not exists idx_profiles_last_activity_at
  on public.profiles(last_activity_at);

create table if not exists public.reminder_preferences (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email_enabled boolean not null default true,
  weekly_pending_enabled boolean not null default true,
  inactive_enabled boolean not null default true,
  motivational_enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.reminder_preferences enable row level security;

create index if not exists idx_reminder_preferences_email_enabled
  on public.reminder_preferences(email_enabled);

alter table public.reminder_logs
  add column if not exists dedupe_key text;

alter table public.reminder_logs
  add column if not exists reason text;

alter table public.reminder_logs
  add column if not exists metadata jsonb not null default '{}'::jsonb;

create unique index if not exists idx_reminder_logs_dedupe_key
  on public.reminder_logs(dedupe_key)
  where dedupe_key is not null;

alter table public.notifications
  add column if not exists reminder_log_id uuid references public.reminder_logs(id) on delete set null;

create index if not exists idx_notifications_reminder_log_id
  on public.notifications(reminder_log_id);

alter table public.email_logs
  add column if not exists reminder_log_id uuid references public.reminder_logs(id) on delete set null;

create index if not exists idx_email_logs_reminder_log_id
  on public.email_logs(reminder_log_id);

-- Reminder logs are generated by trusted scheduler/admin code. Normal users may
-- read their own history but should not forge reminder records through direct RLS access.
drop policy if exists "Users can insert own reminder logs" on public.reminder_logs;

drop policy if exists "Admins can manage reminder logs" on public.reminder_logs;
create policy "Admins can manage reminder logs"
on public.reminder_logs
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Users can view own reminder preferences" on public.reminder_preferences;
create policy "Users can view own reminder preferences"
on public.reminder_preferences
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can insert own reminder preferences" on public.reminder_preferences;
create policy "Users can insert own reminder preferences"
on public.reminder_preferences
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can update own reminder preferences" on public.reminder_preferences;
create policy "Users can update own reminder preferences"
on public.reminder_preferences
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Admins can manage reminder preferences" on public.reminder_preferences;
create policy "Admins can manage reminder preferences"
on public.reminder_preferences
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop trigger if exists update_reminder_preferences_updated_at on public.reminder_preferences;
create trigger update_reminder_preferences_updated_at
before update on public.reminder_preferences
for each row execute procedure public.update_updated_at_column();
